###
### Enable sudo (required for docker service)
###
sudo: required


###
### Attach services
###
services:
  - docker


###
### Global variables
###
env:
  global:
    - MY_DOCKER_NAME="my-db-docker"
    - MY_MYSQL_PASS="toor"


###
### Show information
###
before_install:
  # Get newer docker version
  - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get update; then break; else i=$((i+1)); fi done
  - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce; then break; else i=$((i+1)); fi done
  # Get newer docker-compose version
  - curl -L --retry 100 --retry-max-time 0 https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv -f docker-compose /usr/local/bin
  # List versions
  - docker version
  - docker-compose version


###
### Install
###
install:

  # Create overview section script
  - echo "#!/bin/sh" > /tmp/section.sh
  - echo " echo '===================================================================================================='" >> /tmp/section.sh
  - echo " echo '===================================================================================================='" >> /tmp/section.sh
  - echo " echo \"= \${1}\"" >> /tmp/section.sh
  - echo " echo '===================================================================================================='" >> /tmp/section.sh
  - echo " echo '===================================================================================================='" >> /tmp/section.sh
  - chmod +x /tmp/section.sh

  # Create directories
  - mkdir -p /tmp/mysql-log
  - mkdir -p /tmp/mysql-sock
  - mkdir -p /tmp/mysql-conf
  - mkdir -p /tmp/mysql-data1
  - mkdir -p /tmp/mysql-data2

  # Pre-create logfiles
  - touch /tmp/mysql-log/error.log
  - touch /tmp/mysql-log/mysql.log

  # Set permission
  - chmod -R 777 /tmp/mysql-log
  - chmod -R 777 /tmp/mysql-sock
  - chmod -R 777 /tmp/mysql-conf
  - chmod -R 777 /tmp/mysql-data1
  - chmod -R 777 /tmp/mysql-data1

  # Show Docker version
  - docker version

  # Build my docker
  - docker build -t cytopia/${MY_DOCKER_NAME} .


before_script:

  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/mysql stop || true
  - sudo /etc/init.d/postgresql stop || true
  - sudo service mysql stop || true
  - sudo service postgresql stop || true


###
### Test
###
script:

  ################################################################################
  ## 01.) [a](DEBUG) Test plain docker
  ################################################################################
  - /tmp/section.sh "01.) [a](DEBUG) Test plain docker"
  - docker run --rm
      -p 127.0.0.1:3306:3306
      -e DEBUG_COMPOSE_ENTRYPOINT=1
      -e MYSQL_ROOT_PASSWORD=${MY_MYSQL_PASS}
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME} &
  - sleep 30

  - docker ps

  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "CREATE DATABASE mycustomdatabase DEFAULT CHARACTER SET = 'utf8';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%socket%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%general%log%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%innodb%buffer%pool%size%';"


  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}" || true

  ##
  ## 01.) [b](SILENT) Test plain docker
  ##
  - /tmp/section.sh "01.) [b](SILENT) Test plain docker"
  - docker run --rm
      -p 127.0.0.1:3306:3306
      -e MYSQL_ROOT_PASSWORD=${MY_MYSQL_PASS}
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME} &
  - sleep 30

  - docker ps

  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "CREATE DATABASE mycustomdatabase DEFAULT CHARACTER SET = 'utf8';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%socket%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%general%log%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%innodb%buffer%pool%size%';"

  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}" || true


  ################################################################################
  ## 02.) [a](DEBUG) With logging
  ################################################################################
  - /tmp/section.sh "02.) [a](DEBUG) With logging"
  - docker run --rm
      -p 127.0.0.1:3306:3306
      -v /tmp/mysql-log:/var/log/mysql
      -e DEBUG_COMPOSE_ENTRYPOINT=1
      -e MYSQL_GENERAL_LOG=1
      -e MYSQL_ROOT_PASSWORD=${MY_MYSQL_PASS}
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME} &
  - sleep 30

  - docker ps

  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "CREATE DATABASE mycustomdatabase DEFAULT CHARACTER SET = 'utf8';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%socket%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%general%log%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%innodb%buffer%pool%size%';"

  # Validate log file
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%general%log%';" | grep 'ON'

  - ls -la /tmp/mysql-log
  - tail -10 /tmp/mysql-log/error.log
  - tail -10 /tmp/mysql-log/mysql.log

  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}" || true

  ##
  ## 02.) [b](SILENT) With logging
  ##
  - /tmp/section.sh "02.) [b](SILENT) With logging"
  - docker run --rm
      -p 127.0.0.1:3306:3306
      -v /tmp/mysql-log:/var/log/mysql
      -e MYSQL_GENERAL_LOG=1
      -e MYSQL_ROOT_PASSWORD=${MY_MYSQL_PASS}
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME} &
  - sleep 30

  - docker ps

  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "CREATE DATABASE mycustomdatabase DEFAULT CHARACTER SET = 'utf8';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%socket%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%general%log%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%innodb%buffer%pool%size%';"

  # Validate log file
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%general%log%';" | grep 'ON'

  - ls -la /tmp/mysql-log
  - tail -10 /tmp/mysql-log/error.log
  - tail -10 /tmp/mysql-log/mysql.log

  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}" || true


  ################################################################################
  ## 03.) [a](DEBUG) With config overwrite
  ################################################################################
  - /tmp/section.sh "03.) [a](DEBUG) With config overwrite"
  - printf "[mysqld]\n%s\n" "innodb-buffer-pool-size = 536870912" > /tmp/mysql-conf/buffer.cnf

  - docker run --rm
      -p 127.0.0.1:3306:3306
      -v /tmp/mysql-conf:/etc/mysql/conf.d
      -e DEBUG_COMPOSE_ENTRYPOINT=1
      -e MYSQL_ROOT_PASSWORD=${MY_MYSQL_PASS}
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME} &
  - sleep 30

  - docker ps

  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "CREATE DATABASE mycustomdatabase DEFAULT CHARACTER SET = 'utf8';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%socket%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%general%log%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%innodb%buffer%pool%size%';"

  # Validate configuration file
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%innodb%buffer%pool%size%';" | grep '536870912'

  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}" || true
  - rm -f /tmp/mysql-conf/buffer.cnf

  ##
  ## 03.) [b](SILENT) With config overwrite
  ##
  - /tmp/section.sh "03.) [b](SILENT) With config overwrite"
  - printf "[mysqld]\n%s\n" "innodb-buffer-pool-size = 536870912" > /tmp/mysql-conf/buffer.cnf

  - docker run --rm
      -p 127.0.0.1:3306:3306
      -v /tmp/mysql-conf:/etc/mysql/conf.d
      -e MYSQL_ROOT_PASSWORD=${MY_MYSQL_PASS}
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME} &
  - sleep 30

  - docker ps

  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "CREATE DATABASE mycustomdatabase DEFAULT CHARACTER SET = 'utf8';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%socket%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%general%log%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%innodb%buffer%pool%size%';"

  # Validate configuration file
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%innodb%buffer%pool%size%';" | grep '536870912'

  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}" || true
  - rm -f /tmp/mysql-conf/buffer.cnf


  ################################################################################
  ## 04.) [a](DEBUG) Change socket path
  ################################################################################
  - /tmp/section.sh "04.) [a](DEBUG) Change socket path"
  - docker run --rm
      -p 127.0.0.1:3306:3306
      -e MYSQL_SOCKET_DIR=/usr/local/mysqld-sock
      -e DEBUG_COMPOSE_ENTRYPOINT=1
      -e MYSQL_ROOT_PASSWORD=${MY_MYSQL_PASS}
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME} &
  - sleep 30

  - docker ps

  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "CREATE DATABASE mycustomdatabase DEFAULT CHARACTER SET = 'utf8';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%socket%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%general%log%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%innodb%buffer%pool%size%';"

  # Validate configuration file
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%socket%';" | grep '/usr/local/mysqld-sock/mysqld.sock'

  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}" || true

  ##
  ## 04.) [b](SILENT) Change socket path
  ##
  - /tmp/section.sh "04.) [b](SILENT) Change socket path"
  - docker run --rm
      -p 127.0.0.1:3306:3306
      -e MYSQL_SOCKET_DIR=/usr/local/mysqld-sock
      -e MYSQL_ROOT_PASSWORD=${MY_MYSQL_PASS}
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME} &
  - sleep 30

  - docker ps

  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "CREATE DATABASE mycustomdatabase DEFAULT CHARACTER SET = 'utf8';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%socket%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%general%log%';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%innodb%buffer%pool%size%';"

  # Validate configuration file
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW VARIABLES WHERE Variable_name LIKE '%socket%';" | grep '/usr/local/mysqld-sock/mysqld.sock'

  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}" || true


  ################################################################################
  ## 05.) [a](DEBUG) Mount database dir and re-use it
  ################################################################################
  # FIRST RUN
  - /tmp/section.sh "05.) [a](DEBUG) Mount database dir and re-use it"
  - docker run --rm
      -p 127.0.0.1:3306:3306
      -v /tmp/mysql-data1:/var/lib/mysql
      -e MYSQL_SOCKET_DIR=/usr/local/mysqld-sock
      -e DEBUG_COMPOSE_ENTRYPOINT=1
      -e MYSQL_ROOT_PASSWORD=${MY_MYSQL_PASS}
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME} &
  - sleep 30

  - docker ps

  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "CREATE DATABASE mycustomdatabase DEFAULT CHARACTER SET = 'utf8';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"

  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}" || true
  # SECOND RUN
  - docker run --rm
      -p 127.0.0.1:3306:3306
      -v /tmp/mysql-data1:/var/lib/mysql
      -e MYSQL_SOCKET_DIR=/usr/local/mysqld-sock
      -e DEBUG_COMPOSE_ENTRYPOINT=1
      -e MYSQL_ROOT_PASSWORD=${MY_MYSQL_PASS}
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME} &
  - sleep 30

  - docker ps

  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;" | grep 'mycustomdatabase'

  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}" || true

  ##
  ## 05.) [b](SILENT) Mount database dir and re-use it
  ##
  # FIRST RUN
  - /tmp/section.sh "05.) [b](SILENT) Mount database dir and re-use it"
  - docker run --rm
      -p 127.0.0.1:3306:3306
      -v /tmp/mysql-data2:/var/lib/mysql
      -e MYSQL_SOCKET_DIR=/usr/local/mysqld-sock
      -e MYSQL_ROOT_PASSWORD=${MY_MYSQL_PASS}
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME} &
  - sleep 30

  - docker ps

  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "CREATE DATABASE mycustomdatabase DEFAULT CHARACTER SET = 'utf8';"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"

  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}" || true
  # SECOND RUN
  - docker run --rm
      -p 127.0.0.1:3306:3306
      -v /tmp/mysql-data2:/var/lib/mysql
      -e MYSQL_SOCKET_DIR=/usr/local/mysqld-sock
      -e DEBUG_COMPOSE_ENTRYPOINT=1
      -e MYSQL_ROOT_PASSWORD=${MY_MYSQL_PASS}
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME} &
  - sleep 30

  - docker ps

  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;"
  - mysql --user=root --password=${MY_MYSQL_PASS} --host=127.0.0.1 -e "SHOW DATABASES;" | grep 'mycustomdatabase'

  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}" || true
